apiVersion: apps/v1
kind: Deployment
metadata:
  name: instant-pay-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: instant-pay-gateway-service
  template:
    metadata:
      labels:
        component: instant-pay-gateway-service
    spec:
      containers:
        - name: instant-pay-gateway
          image: index.docker.io/octopussolutionsengineering/ghu-instant-pay-gateway:25.12.09182001
          ports:
            - name: http-route
              containerPort: 80
